# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import detection_service_pb2 as detection__service__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in detection_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class DetectionServiceStub(object):
    """==================== Service Definition ====================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectPerson = channel.unary_unary(
                '/detection.DetectionService/DetectPerson',
                request_serializer=detection__service__pb2.DetectPersonRequest.SerializeToString,
                response_deserializer=detection__service__pb2.DetectPersonResponse.FromString,
                _registered_method=True)
        self.DetectFace = channel.unary_unary(
                '/detection.DetectionService/DetectFace',
                request_serializer=detection__service__pb2.DetectFaceRequest.SerializeToString,
                response_deserializer=detection__service__pb2.DetectFaceResponse.FromString,
                _registered_method=True)
        self.RecognizeFace = channel.unary_unary(
                '/detection.DetectionService/RecognizeFace',
                request_serializer=detection__service__pb2.RecognizeFaceRequest.SerializeToString,
                response_deserializer=detection__service__pb2.RecognizeFaceResponse.FromString,
                _registered_method=True)
        self.AnalyzeBehavior = channel.unary_unary(
                '/detection.DetectionService/AnalyzeBehavior',
                request_serializer=detection__service__pb2.AnalyzeBehaviorRequest.SerializeToString,
                response_deserializer=detection__service__pb2.AnalyzeBehaviorResponse.FromString,
                _registered_method=True)
        self.FullAnalysis = channel.unary_unary(
                '/detection.DetectionService/FullAnalysis',
                request_serializer=detection__service__pb2.FullAnalysisRequest.SerializeToString,
                response_deserializer=detection__service__pb2.FullAnalysisResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/detection.DetectionService/HealthCheck',
                request_serializer=detection__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=detection__service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class DetectionServiceServicer(object):
    """==================== Service Definition ====================

    """

    def DetectPerson(self, request, context):
        """Person detection with tracking + behavior (PRIMARY endpoint)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectFace(self, request, context):
        """Face detection (standalone)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizeFace(self, request, context):
        """Face recognition + resident matching
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeBehavior(self, request, context):
        """Behavior analysis from pre-detected persons
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FullAnalysis(self, request, context):
        """Full pipeline in one call (recommended for streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DetectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectPerson': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectPerson,
                    request_deserializer=detection__service__pb2.DetectPersonRequest.FromString,
                    response_serializer=detection__service__pb2.DetectPersonResponse.SerializeToString,
            ),
            'DetectFace': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectFace,
                    request_deserializer=detection__service__pb2.DetectFaceRequest.FromString,
                    response_serializer=detection__service__pb2.DetectFaceResponse.SerializeToString,
            ),
            'RecognizeFace': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeFace,
                    request_deserializer=detection__service__pb2.RecognizeFaceRequest.FromString,
                    response_serializer=detection__service__pb2.RecognizeFaceResponse.SerializeToString,
            ),
            'AnalyzeBehavior': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeBehavior,
                    request_deserializer=detection__service__pb2.AnalyzeBehaviorRequest.FromString,
                    response_serializer=detection__service__pb2.AnalyzeBehaviorResponse.SerializeToString,
            ),
            'FullAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.FullAnalysis,
                    request_deserializer=detection__service__pb2.FullAnalysisRequest.FromString,
                    response_serializer=detection__service__pb2.FullAnalysisResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=detection__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=detection__service__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'detection.DetectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('detection.DetectionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DetectionService(object):
    """==================== Service Definition ====================

    """

    @staticmethod
    def DetectPerson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/detection.DetectionService/DetectPerson',
            detection__service__pb2.DetectPersonRequest.SerializeToString,
            detection__service__pb2.DetectPersonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectFace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/detection.DetectionService/DetectFace',
            detection__service__pb2.DetectFaceRequest.SerializeToString,
            detection__service__pb2.DetectFaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecognizeFace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/detection.DetectionService/RecognizeFace',
            detection__service__pb2.RecognizeFaceRequest.SerializeToString,
            detection__service__pb2.RecognizeFaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeBehavior(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/detection.DetectionService/AnalyzeBehavior',
            detection__service__pb2.AnalyzeBehaviorRequest.SerializeToString,
            detection__service__pb2.AnalyzeBehaviorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FullAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/detection.DetectionService/FullAnalysis',
            detection__service__pb2.FullAnalysisRequest.SerializeToString,
            detection__service__pb2.FullAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/detection.DetectionService/HealthCheck',
            detection__service__pb2.HealthCheckRequest.SerializeToString,
            detection__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
